server.port=8761
spring.application.name=discovery-server

eureka.instance.hostname=localhost
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# Fast Eviction of Stopped Instances (No Stale Services)
eureka.server.enable-self-preservation=false
eureka.server.eviction-interval-timer-in-ms=10000
eureka.instance.lease-renewal-interval-in-seconds=5
eureka.instance.lease-expiration-duration-in-seconds=10

logging.level.root=INFO
logging.level.com.netflix.eureka=WARN
logging.level.com.netflix.eureka.registry=WARN
logging.level.com.netflix.discovery=WARN
